import type {
  PainProblem,
  PainValidation,
  ProductConcept,
  AdTargeting,
  LaunchSummary,
  ForgeSession,
} from "@/types";

export const MOCK_PAINS: PainProblem[] = [
  {
    id: "p1",
    number: 1,
    name: "The Silent Fibroid Sufferer",
    whoSuffers: "Women aged 28–45, often newly married or trying to conceive, Nigerian and diaspora",
    rawPain: "I have been bleeding heavily for months and I am exhausted all the time but I cannot tell anyone — not even my husband. I have tried everything the doctor gave me but nothing is working. I am terrified I will never have children and my marriage will fall apart.",
    whySurvivalLevel: "Fertility is tied to identity, marriage security, and cultural worth — she cannot ignore it.",
    culturalAngle: "In Nigerian culture, childlessness can threaten a marriage; the shame is immense and the pressure from in-laws is suffocating.",
  },
  {
    id: "p2",
    number: 2,
    name: "The Bedwetting Parent's Shame",
    whoSuffers: "Parents of children aged 6–14 who still wet the bed, across Nigeria and diaspora",
    rawPain: "My 10-year-old is still wetting the bed and I have no idea what to do. He cannot go to school trips or sleep at grandma's. I feel like a failure as a parent and every night is a source of dread for both of us.",
    whySurvivalLevel: "A child's suffering and a parent's helplessness — this person will pay anything that works.",
    culturalAngle: "African families often attribute bedwetting to spiritual causes; parents are caught between traditional blame and medical confusion.",
  },
  {
    id: "p3",
    number: 3,
    name: "The Man Who Cannot Perform",
    whoSuffers: "Men aged 30–55, married or in relationships, too ashamed to see a doctor",
    rawPain: "It has been happening for months and I cannot talk to anyone about it. Not my doctor, not my friend, not my wife. I feel less than a man. I have tried everything I saw online but nothing works for more than a week.",
    whySurvivalLevel: "Sexual identity is core to how men perceive their worth — this is existential.",
    culturalAngle: "African men are expected to be virile; erectile issues carry deep shame and are never discussed openly. Witchcraft is often blamed.",
  },
  {
    id: "p4",
    number: 4,
    name: "The Post-Baby Body That Won't Bounce Back",
    whoSuffers: "New mothers aged 24–38, feeling invisible and unattractive after childbirth",
    rawPain: "My body does not look like mine anymore. My husband tries to be kind but I can see the difference. I do not recognise myself in the mirror. I have tried every diet but the belly fat just sits there, mocking me.",
    whySurvivalLevel: "Body image and marital attraction are intertwined — she fears losing her husband's desire.",
    culturalAngle: "Nigerian women face enormous post-pregnancy pressure; the expectation to 'bounce back' is extreme but resources are scarce.",
  },
  {
    id: "p5",
    number: 5,
    name: "The Diabetic Who Won't Change",
    whoSuffers: "Adults 40–65 with type 2 diabetes, overwhelmed by conflicting advice",
    rawPain: "I have been told to change my diet for years but I cannot give up my food. I am Nigerian — I cannot just stop eating eba and soup. I am scared of going blind or losing a limb but I do not know where to start without giving up everything I love.",
    whySurvivalLevel: "Fear of amputation and blindness is visceral survival fear.",
    culturalAngle: "Nigerian diet and diabetes management are rarely covered together; cultural food is the core obstacle.",
  },
  {
    id: "p6",
    number: 6,
    name: "The Smell Nobody Talks About",
    whoSuffers: "Adults 18–45 suffering from chronic body or vaginal odour despite good hygiene",
    rawPain: "I shower twice a day. I spend a fortune on deodorant and wipes. But I can still smell it. I am terrified someone else can too. I avoid crowds, cancel plans, and have not been intimate in months. I am so ashamed I have never told anyone.",
    whySurvivalLevel: "Social paralysis and intimate avoidance — she is shrinking her entire life to hide this.",
    culturalAngle: "Vaginal odour is deeply taboo across African cultures; women suffer in silence rather than seek help.",
  },
  {
    id: "p7",
    number: 7,
    name: "The Insomniac Who Dreads Nightfall",
    whoSuffers: "Professionals and mothers 28–50 who cannot sleep despite exhaustion",
    rawPain: "I am exhausted by 9pm but the moment I lie down my brain will not stop. I have been awake until 3am for months. I cannot function at work, I snap at my children, and I am terrified there is something wrong with me.",
    whySurvivalLevel: "Cognitive and emotional collapse — work and parenting are both at risk.",
    culturalAngle: "Sleep disorders are rarely discussed in Nigerian families; prayer and 'trying harder' are the prescribed solutions.",
  },
  {
    id: "p8",
    number: 8,
    name: "The Hidden Hair Loss Crisis",
    whoSuffers: "Women aged 25–45, losing hair to stress, postpartum hormones, or traction alopecia",
    rawPain: "My hairline is going and I am only 32. I have been wearing wigs for two years to hide it. I am terrified it will never grow back. I have spent so much money on products that did nothing.",
    whySurvivalLevel: "Hair is deeply tied to femininity and self-worth — she feels her identity is dissolving.",
    culturalAngle: "Traction alopecia from braiding and weaves is epidemic in the African diaspora but rarely addressed honestly.",
  },
  {
    id: "p9",
    number: 9,
    name: "The Chronic Fatigue No Doctor Can Explain",
    whoSuffers: "Women 30–50 who are exhausted no matter how much they sleep",
    rawPain: "I have done every test. The doctors say everything is fine. But I wake up tired. I drag through the day. My family thinks I am lazy. I think something is seriously wrong with me but nobody believes me.",
    whySurvivalLevel: "Being dismissed by medicine while genuinely suffering creates desperate, motivated buyers.",
    culturalAngle: "African women often have fatigue dismissed as laziness or spiritual attack — the gap between medical explanation and lived reality is vast.",
  },
  {
    id: "p10",
    number: 10,
    name: "The Child Who Won't Eat",
    whoSuffers: "Mothers of toddlers and young children aged 1–8 who refuse food",
    rawPain: "My child has not eaten properly in weeks. I am terrified he is malnourished. I have tried everything and I am at my wit's end. My mother-in-law says it is because I am not cooking the right things. I feel like a failure every single day.",
    whySurvivalLevel: "A mother's fear for her child's health combined with family pressure — instant buyer.",
    culturalAngle: "In-law pressure around feeding practices is intense in Nigerian families; this mother is under attack from multiple directions.",
  },
  {
    id: "p11",
    number: 11,
    name: "The Gut That Ruins Everything",
    whoSuffers: "Adults 20–45 with chronic bloating, IBS, or digestive pain that disrupts daily life",
    rawPain: "I am bloated every single day. It does not matter what I eat. I look pregnant after meals and the pain is embarrassing. I have cancelled plans, avoided dates, and stopped wearing fitted clothes. Nobody understands how much this affects my life.",
    whySurvivalLevel: "Daily physical pain combined with social restriction — the impact is total.",
    culturalAngle: "Heavy Nigerian foods (beans, starchy staples) worsen bloating; many sufferers have no idea diet is the cause.",
  },
  {
    id: "p12",
    number: 12,
    name: "The Menopause Nobody Warned Her About",
    whoSuffers: "Women 42–58 experiencing symptoms they do not understand",
    rawPain: "I am having hot flashes in the middle of meetings and I cannot sleep. My mood is all over the place and my husband thinks I have lost my mind. Nobody told me it would be this bad. I am too embarrassed to talk to anyone.",
    whySurvivalLevel: "Loss of emotional and physical control is terrifying — she desperately wants answers.",
    culturalAngle: "Menopause is rarely discussed openly in Nigerian or African communities; women suffer alone thinking they are going mad.",
  },
  {
    id: "p13",
    number: 13,
    name: "The Man Who Can't Lose the Belly",
    whoSuffers: "Men aged 35–55 with stubborn abdominal fat despite effort",
    rawPain: "I have been trying to lose this belly for two years. I have done the gym on and off, tried cutting carbs, but it just stays there. My wife used to grab my stomach playfully and now she says nothing. I feel old and unattractive.",
    whySurvivalLevel: "Vanity, marital intimacy, and health fears all converge here.",
    culturalAngle: "The 'big man belly' is culturally associated with success in Nigeria but increasingly stigmatised; the tension creates motivated buyers.",
  },
  {
    id: "p14",
    number: 14,
    name: "The Skin Bleaching Shame Spiral",
    whoSuffers: "Women and some men 18–40 who have used bleaching products and are afraid of the damage",
    rawPain: "I started using products years ago and now my skin looks patchy and damaged. I am too embarrassed to stop because without the products I look worse. I am terrified of what I have done to myself but I cannot tell anyone.",
    whySurvivalLevel: "Trapped in a self-reinforcing cycle she is too ashamed to break — desperate for a way out.",
    culturalAngle: "Skin bleaching is widespread and deeply taboo across Nigeria and West Africa; the damage is common and rarely addressed honestly.",
  },
  {
    id: "p15",
    number: 15,
    name: "The PCOS Diagnosis With No Roadmap",
    whoSuffers: "Women 18–38 diagnosed with PCOS, overwhelmed and trying to conceive",
    rawPain: "My doctor told me I have PCOS and then sent me home with a leaflet. I have irregular periods, I am gaining weight I cannot control, and I am terrified I cannot have children. I have been researching for months but everything contradicts everything else.",
    whySurvivalLevel: "Fertility fear plus medical abandonment — this woman will pay for clarity and hope.",
    culturalAngle: "PCOS is poorly understood in Nigerian medical culture; cultural pressure to conceive makes every month without pregnancy more devastating.",
  },
];

export const MOCK_VALIDATIONS: PainValidation[] = [
  {
    painId: "p1",
    painName: "The Silent Fibroid Sufferer",
    survivalTest: {
      urgency: { score: "YES", reason: "Heavy bleeding and fertility timeline create immediate pressure" },
      embarrassment: { score: "YES", reason: "Sexual and reproductive health is deeply taboo in Nigerian culture" },
      failedAttempts: { score: "YES", reason: "Medical treatments have failed; she is actively searching for alternatives" },
      identityThreat: { score: "YES", reason: "Childlessness threatens her identity as a wife and woman" },
      immediateSpend: { score: "YES", reason: "Fertility desperation bypasses price sensitivity entirely" },
      total: 5,
    },
    marketCheck: {
      searchVolume: { score: "PASS", reason: "Millions of searches for 'fibroid natural treatment' and 'shrink fibroids naturally'" },
      facebookTargeting: { score: "PASS", reason: "Women 25-45, interests: fertility, women's health, Nigerian parenting groups" },
      competitorPresence: { score: "PASS", reason: "Strong competitor presence confirms market — gap exists for culturally-relevant protocols" },
      crossMarketAppeal: { score: "PASS", reason: "Both Nigerian women and UK/US diaspora are acutely affected" },
      lowTicketThreshold: { score: "PASS", reason: "₦9,800 is negligible compared to hospital bills and fertility treatments" },
      verdict: "STRONG",
    },
    combinedVerdict: "EXCELLENT",
  },
  {
    painId: "p3",
    painName: "The Man Who Cannot Perform",
    survivalTest: {
      urgency: { score: "YES", reason: "Every intimate moment is a live threat — urgency is constant" },
      embarrassment: { score: "YES", reason: "Men will not discuss this with anyone, making online solutions uniquely appealing" },
      failedAttempts: { score: "YES", reason: "Pills, supplements, and searches have all failed — desperation is high" },
      identityThreat: { score: "YES", reason: "Masculinity is directly under attack — this is identity-level" },
      immediateSpend: { score: "YES", reason: "Men spend thousands on this category without hesitation if the promise is right" },
      total: 5,
    },
    marketCheck: {
      searchVolume: { score: "PASS", reason: "One of the highest-volume health search categories globally" },
      facebookTargeting: { score: "PASS", reason: "Men 35-55, interests: men's health, relationships, fitness — private browsing intent is high" },
      competitorPresence: { score: "PASS", reason: "Huge competitor presence — cultural/ancestral angle is an untapped differentiator" },
      crossMarketAppeal: { score: "PASS", reason: "Universal pain with Nigerian men in Nigeria and diaspora equally affected" },
      lowTicketThreshold: { score: "PASS", reason: "Men pay premium for discretion — low price is a conversion accelerator" },
      verdict: "STRONG",
    },
    combinedVerdict: "EXCELLENT",
  },
  {
    painId: "p6",
    painName: "The Smell Nobody Talks About",
    survivalTest: {
      urgency: { score: "YES", reason: "Social and intimate life is on hold — every day is urgent" },
      embarrassment: { score: "YES", reason: "Perhaps the single most shameful health problem a person can have" },
      failedAttempts: { score: "YES", reason: "Standard hygiene has failed; she has been searching incognito for months" },
      identityThreat: { score: "YES", reason: "She avoids intimacy, social contact — her whole life is shrinking" },
      immediateSpend: { score: "YES", reason: "Would pay almost any price for a guaranteed solution" },
      total: 5,
    },
    marketCheck: {
      searchVolume: { score: "PASS", reason: "Extremely high incognito search volume — one of the top shame searches" },
      facebookTargeting: { score: "MARGINAL", reason: "Women's health interests work but ad copy must be delicate to pass review" },
      competitorPresence: { score: "PASS", reason: "Some competitors but mostly generic — room for specific, culturally aware product" },
      crossMarketAppeal: { score: "PASS", reason: "Universal problem; Nigerian and diaspora women equally affected" },
      lowTicketThreshold: { score: "PASS", reason: "Shame converts instantly at low price — no hesitation if the promise is specific" },
      verdict: "STRONG",
    },
    combinedVerdict: "EXCELLENT",
  },
];

export const MOCK_PRODUCT_CONCEPT: ProductConcept = {
  painId: "p1",
  buyerAvatar: {
    name: "Amara",
    age: "34",
    gender: "Female",
    location: "Primary: Lagos, Nigeria | Secondary: London, UK",
    lifeStage: "Married 3 years, trying to conceive, diagnosed with fibroids",
    painInOwnWords:
      "I have been married for three years and everyone is asking when the baby is coming. My husband is patient but I can see the worry in his eyes. I bleed so heavily every month that I have missed work. I went to the hospital and they want to operate but I am terrified. I have been Googling at 2am every night looking for something, anything, that does not involve surgery.",
    failedSolutions: [
      "Prescribed hormones — caused weight gain and mood swings with no improvement",
      "Herbal teas from the market — no measurable difference after 3 months",
      "Diet changes (reducing red meat) — periods still heavy",
      "Prayer and fasting — did not remove the fibroids",
      "Expensive supplement stacks — no change in scan results",
    ],
    perfectOutcome:
      "Her fibroids shrink enough that her periods become manageable, her energy returns, and her doctor confirms improvement on the scan. She conceives within the year. Her mother-in-law stops asking questions. She feels like herself again.",
    buyingTrigger:
      "A specific protocol that names her exact situation — heavy bleeding, trying to conceive, afraid of surgery — and offers a traditional/ancestral framework she can trust without feeling like she is betraying her faith or culture.",
  },
  framework: {
    corePromise: "A 60-day natural fibroid protocol that reduces heavy bleeding within 3 weeks and supports hormonal balance without surgery or synthetic hormones.",
    format: "Step-by-Step Protocol PDF with daily tracking",
    phase1Diagnose:
      "Identify the root hormonal imbalance driving fibroid growth — oestrogen dominance, liver sluggishness, or inflammatory diet — using a simple self-assessment quiz included in the PDF.",
    phase2Apply:
      "Daily 3-phase action plan: anti-oestrogenic foods to add (with Nigerian meal substitutions), specific herbs from traditional African medicine (turmeric, moringa, ginger protocol), and the lymphatic drainage routine to reduce pelvic congestion. Weeks 1-4 focus on bleeding reduction; weeks 5-8 focus on shrinkage support.",
    phase3Maintain:
      "Monthly maintenance cycle aligned with her menstrual phases, so the work compounds over time without willpower or restriction.",
    quickWin:
      "The Day 1 Castor Oil Pack Ritual — a 30-minute pelvic compress using ingredients from any Nigerian market that most women report reduces cramping within 48 hours.",
    toolsIncluded: [
      "Fibroid Root Cause Self-Assessment Quiz",
      "60-Day Daily Tracking Calendar",
      "Anti-Fibroid Nigerian Meal Plan (with local ingredient swaps)",
      "Herbal Supplement Dosing Chart (what to buy, where, how much)",
      "Castor Oil Pack Step-by-Step Picture Guide",
      "Symptom Tracking Chart (bleeding, pain, energy)",
      "What to Show Your Doctor: Monitoring Milestones",
    ],
    credibilityMechanism:
      "Anchored in West African traditional medicine — specifically the herbal protocols used by traditional birth attendants across Yoruba and Igbo communities, crossreferenced with modern phytoestrogen research.",
  },
  titles: [
    {
      number: 1,
      architecture: "Ancestral",
      fullTitle: "Mama Ngozi's Fibroid Melter Protocol",
      subtitle: "The 60-Day Ancestral Remedy That Reduces Heavy Bleeding and Supports Natural Fibroid Shrinkage — Without Surgery",
      painAddressed: "Heavy fibroid bleeding, fertility fears, desperation for a natural alternative to surgery",
      transformationPromised: "Clinically-informed ancestral protocol that shrinks fibroids and restores hope",
      emotionalHook: "Recognition and trust — 'someone like my grandmother solved this'",
      facebookAdTest: { passes: true, reason: "Stops the scroll for any Nigerian woman who has been Googling fibroids at night" },
    },
    {
      number: 2,
      architecture: "Ancestral",
      fullTitle: "The Old Wives Were Right: Grandma Ada's Fibroid Cleanse",
      subtitle: "Ancient Igbo Wisdom Meets Modern Hormonal Science in a 60-Day Protocol for Heavy Bleeding and Natural Fibroid Reduction",
      painAddressed: "Distrust of Western medicine, desire for culturally-grounded solutions",
      transformationPromised: "Reclaiming ancestral healing knowledge that actually works",
      emotionalHook: "Cultural pride and curiosity — 'what did our grandmothers know that doctors don't?'",
      facebookAdTest: { passes: true, reason: "The cultural curiosity hook is powerful for Nigerian and diaspora women" },
    },
    {
      number: 3,
      architecture: "Scientific",
      fullTitle: "The Oestrogen Dominance Reversal Protocol",
      subtitle: "A 60-Day Step-by-Step System to Reduce Fibroid-Feeding Hormones, Stop Heavy Bleeding, and Support Natural Fibroid Shrinkage",
      painAddressed: "Women who trust science and want a mechanistic explanation for their suffering",
      transformationPromised: "Taking control through understanding — finally knowing WHY this is happening",
      emotionalHook: "Relief and empowerment — 'I finally understand what is going on in my body'",
      facebookAdTest: { passes: true, reason: "Targets educated professional women aged 30-45 very effectively" },
    },
    {
      number: 4,
      architecture: "Scientific",
      fullTitle: "The 60-Day Fibroid Reduction Blueprint",
      subtitle: "A Clinically-Informed, Food-First Protocol to Reduce Heavy Bleeding in 3 Weeks and Support Hormonal Balance Without Surgery",
      painAddressed: "The overwhelm of contradictory medical advice",
      transformationPromised: "A clear, structured plan where there was previously chaos",
      emotionalHook: "Clarity and hope — 'someone has figured this out for me'",
      facebookAdTest: { passes: true, reason: "Direct benefit-led headline with specific timeframe — strong converter" },
    },
    {
      number: 5,
      architecture: "Blended",
      fullTitle: "No More Surgery: The Nigerian Women's Fibroid Protocol",
      subtitle: "How Thousands of Women Are Using Ancestral Remedies and Hormonal Science to Shrink Fibroids and Reclaim Their Bodies — Without Going Under the Knife",
      painAddressed: "Fear of surgery — the most visceral fibroid fear",
      transformationPromised: "Freedom from the operating table and hope for natural conception",
      emotionalHook: "Urgency and identity — 'this was made specifically for women like me'",
      facebookAdTest: { passes: true, reason: "'No More Surgery' is a powerful scroll-stopper for this exact audience" },
    },
  ],
};

export const MOCK_AD_TARGETING: AdTargeting = {
  primary: {
    ageRange: "25–45",
    gender: "Female",
    interests: [
      "Women's health Nigeria",
      "Fertility awareness",
      "Natural remedies",
      "Traditional African medicine",
      "Nigerian parenting and family groups",
      "Church women's fellowship",
      "Pregnancy and motherhood Nigeria",
    ],
    behaviours: [
      "Engaged shoppers (health products)",
      "Online buyers in last 30 days",
      "Health-conscious women",
    ],
    customAngle: "Target women in religious women's groups — the faith community is where fibroid shame is shared in Nigeria",
  },
  secondary: {
    ageRange: "26–44",
    gender: "Female",
    locations: ["London", "Manchester", "Birmingham", "Houston", "Atlanta", "Toronto", "Calgary"],
    interests: [
      "Diaspora Nigerian communities",
      "African women's health UK",
      "Fertility clinics London",
      "IVF support groups",
      "Natural health remedies",
      "West African cultural groups",
      "Afrobeats and African lifestyle",
    ],
    behaviours: [
      "Frequent international shoppers",
      "Engaged with health content",
      "Online buyers",
    ],
    culturalTargeting: "Target women who follow Nigerian news pages, Nigerian church groups abroad, and African parenting communities in diaspora cities",
  },
  estimatedAudienceSize: "2.5M – 4M (primary Nigeria) + 800K – 1.2M (diaspora Tier 1)",
  hooks: [
    {
      type: "Emotional",
      text: "You have been Googling fibroids at 2am. You are exhausted, scared, and the doctors want to operate. Before you do — read this.",
    },
    {
      type: "Curiosity",
      text: "What Nigerian grandmothers knew about fibroids that your gynaecologist never learned in medical school.",
    },
    {
      type: "Failed Attempts",
      text: "You have tried the hormones. You have tried the herbs. You have tried the diet. Here is what you have not tried — and why it actually works.",
    },
    {
      type: "Identity",
      text: "You were not supposed to have this fight. You are 34, you are married, and you should be starting your family. Fibroids stole that from you. Here is how you take it back.",
    },
    {
      type: "Outcome",
      text: "60 days from now, your periods could be manageable, your energy restored, and your doctor looking at a different scan. Here is the protocol.",
    },
  ],
};

export const MOCK_LAUNCH_SUMMARY: LaunchSummary = {
  niche: "Health & Body — Women's Reproductive Health",
  survivalLevelPain: "A married Nigerian woman in her 30s is silently suffering from heavy fibroid bleeding, terrified of surgery, and desperate to conceive before her marriage and identity fracture completely.",
  avatar: {
    name: "Amara",
    age: "34",
    gender: "Female",
    location: "Lagos (primary) / London (diaspora)",
    lifeStage: "Married 3 years, trying to conceive, living with fibroids",
    painInOwnWords: "I have been Googling at 2am every night. The doctors want to operate but I am terrified. I just need to know there is another way — for my body, my marriage, and my future.",
  },
  productTitle: "Mama Ngozi's Fibroid Melter Protocol",
  subtitle: "The 60-Day Ancestral Remedy That Reduces Heavy Bleeding and Supports Natural Fibroid Shrinkage — Without Surgery",
  format: "Step-by-Step Protocol PDF with daily tracking tools",
  priceNGN: "₦9,800",
  priceUSD: "$9.97",
  corePromise: "Reduce heavy fibroid bleeding within 3 weeks and support natural shrinkage in 60 days using a protocol rooted in West African traditional medicine and modern hormonal science — no surgery required.",
  transformationArc: {
    phase1: "Diagnose: Identify root cause (oestrogen dominance, liver load, or inflammation) using the self-assessment quiz",
    phase2: "Apply: 60-day daily protocol — anti-oestrogenic foods (with Nigerian meal swaps), herbal schedule, and pelvic castor oil ritual",
    phase3: "Maintain: Cyclical monthly maintenance plan that compounds results over time",
  },
  quickWin: "Day 1 Castor Oil Pack Ritual — 30 minutes, local ingredients, most women report reduced cramping within 48 hours",
  toolsIncluded: [
    "Fibroid Root Cause Self-Assessment Quiz",
    "60-Day Daily Tracking Calendar",
    "Anti-Fibroid Nigerian Meal Plan",
    "Herbal Supplement Dosing Chart",
    "Castor Oil Pack Picture Guide",
    "Symptom Tracking Chart",
    "Monitoring Milestones for Doctor Visits",
  ],
  credibilityMechanism: "West African traditional birth attendant protocols crossreferenced with modern phytoestrogen research",
  adTargetingPrimary: "Women 25–45, Nigeria — fertility, women's health, church groups, natural remedies",
  adTargetingSecondary: "Women 26–44, UK/US/Canada diaspora cities — Nigerian communities, African women's health, fertility clinics",
  topHooks: [
    "You have been Googling fibroids at 2am. You are exhausted, scared, and the doctors want to operate. Before you do — read this.",
    "What Nigerian grandmothers knew about fibroids that your gynaecologist never learned in medical school.",
    "60 days from now, your periods could be manageable, your energy restored, and your doctor looking at a different scan. Here is the protocol.",
  ],
  immediateNextStep: "Open your PDF creation tool and write Phase 1 — the Diagnose section. Show Amara you understand exactly what she is going through. Make her feel seen before you fix her.",
};

export const MOCK_SESSIONS: ForgeSession[] = [
  {
    id: "session-1",
    name: "Health — Fibroid Protocol",
    niche: "HEALTH",
    currentStage: 6,
    createdAt: "2026-05-10T09:00:00Z",
    updatedAt: "2026-05-14T16:30:00Z",
  },
  {
    id: "session-2",
    name: "Wealth — Debt Escape Blueprint",
    niche: "WEALTH",
    currentStage: 3,
    createdAt: "2026-05-15T11:00:00Z",
    updatedAt: "2026-05-16T14:00:00Z",
  },
  {
    id: "session-3",
    name: "Relationships — Marriage Rescue",
    niche: "RELATIONSHIPS",
    currentStage: 2,
    createdAt: "2026-05-17T08:00:00Z",
    updatedAt: "2026-05-17T08:45:00Z",
  },
];
